"""Single source of truth for browser domain profiles and selectors."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Mapping
from urllib.parse import urlparse


@dataclass(frozen=True)
class SiteProfile:
    domain: str
    origin: str
    username_selectors: tuple[str, ...]
    code_selectors: tuple[str, ...]
    submit_selector: str
    result_selectors: tuple[str, ...] = ()
    success_markers: tuple[str, ...] = ()
    failure_markers: tuple[str, ...] = ()
    timeout_seconds: float = 5.0
    navigation_timeout_seconds: float = 12.0
    # Số tab warm thực tế cho domain; main_script giới hạn worker không vượt
    # con số này để tránh tranh chấp tab và lỗi "No available tab".
    tab_slots: int = 2
    form_settle_seconds: float = 0.03
    result_timeout_ms: int = 5000
    result_poll_interval: float = 0.10
    selector_fast_window_seconds: float = 0.80
    full_reload_every: int = 100
    # Optional browser-session API observation. XX88 still requires a
    # Cloudflare token generated by the page; this is not a CAPTCHA bypass.
    public_api_endpoint: str | None = None
    api_response_timeout_ms: int = 4500
    api_capture_phase: str = "submit"
    # Nút đóng popup THÔNG BÁO KẾT QUẢ, chỉ bấm SAU khi đã đọc xong kết quả
    # (trong bước dọn trang). Không dùng trước submit vì đây là nút xác nhận.
    #  - popup_dismiss_selectors: CSS selector chính xác (ưu tiên).
    #  - popup_dismiss_texts: chữ KHỚP TOÀN BỘ của nút, và nút phải nằm trong
    #    overlay (position: fixed / role=dialog) để không bấm nhầm nút của trang.
    popup_dismiss_selectors: tuple[str, ...] = ()
    popup_dismiss_texts: tuple[str, ...] = ()

    def validate(self) -> list[str]:
        errors: list[str] = []
        if not self.domain or "." not in self.domain:
            errors.append("domain is missing or invalid")
        if not self.origin.startswith("https://"):
            errors.append("origin must use https")
        if not self.code_selectors:
            errors.append("code_selectors is empty")
        if not self.submit_selector:
            errors.append("submit_selector is empty")
        if self.timeout_seconds <= 0 or self.navigation_timeout_seconds <= 0:
            errors.append("timeouts must be positive")
        if self.tab_slots < 1 or self.form_settle_seconds < 0:
            errors.append("tab_slots/form_settle_seconds are invalid")
        if self.result_timeout_ms <= 0 or self.result_poll_interval <= 0:
            errors.append("result timing is invalid")
        return errors


_COMMON_SUCCESS = ("thành công", "success", "điểm", "received", "approved")
_COMMON_FAILURE = ("sai", "invalid", "đã dùng", "expired", "not found", "error")

# Domain-specific selectors previously duplicated in browser_engine.py now live
# only here. Generic fallback selectors remain in browser_engine.py because they
# are deliberately shared across sites rather than domain configuration.
SITE_PROFILES: dict[str, SiteProfile] = {
    "tangquaqq88.com": SiteProfile(
        "tangquaqq88.com", "https://tangquaqq88.com",
        ("#account-code", "input[placeholder='Nhập tài khoản của bạn']"),
        ("#promo-code", "input[placeholder='Nhập mã CODE']"),
        "button[type='submit'], form button, img[alt='Kiểm tra ngay']",
        result_selectors=("#promo-code ~ [role='alert']", "form [role='alert']", ".swal2-container", "#toast-container"),
        success_markers=_COMMON_SUCCESS, failure_markers=_COMMON_FAILURE,
        tab_slots=1, form_settle_seconds=0.02, result_timeout_ms=3500,
        result_poll_interval=0.05, selector_fast_window_seconds=0.50,
        full_reload_every=150,
        public_api_endpoint="https://api-code-qq88-v2.royalapps.net/client/giftcode",
        api_response_timeout_ms=5000,
        api_capture_phase="verification",
        popup_dismiss_texts=("đồng ý",),
    ),
    "hi88-freecode.pages.dev": SiteProfile(
        "hi88-freecode.pages.dev", "https://hi88-freecode.pages.dev",
        ("input[placeholder='Nhập tài khoản']",),
        ("input[placeholder='Nhập mã']", "input[autocomplete='one-time-code']"),
        "button[aria-label='Kiểm tra ngay'], button[type='submit'], form button",
        result_selectors=("form [role='alert']", "form [role='status']", ".modal-content", ".toast", "[class*='result' i]"),
        success_markers=_COMMON_SUCCESS, failure_markers=_COMMON_FAILURE,
        tab_slots=1, form_settle_seconds=0.03, result_timeout_ms=4500,
        result_poll_interval=0.05, selector_fast_window_seconds=0.60,
        full_reload_every=100,
        public_api_endpoint="https://api-code-hi88-v2.royalapps.net/client",
        api_response_timeout_ms=5000,
        api_capture_phase="verification",
        popup_dismiss_texts=("tiếp tục",),
    ),
    "livemm88.net": SiteProfile(
        "livemm88.net", "https://livemm88.net/nhap-code",
        ("#enter-code-username", "#account-code", "input[name='username']"),
        ("#enter-code-code", "input[name='code']", "input[name='giftcode']",
         "input[autocomplete='one-time-code']", "input[placeholder*='mã code' i]",
         "input[placeholder*='nhập mã' i]", "input[id*='code' i]:not(#enter-code-username)",
         "input[id*='promo' i]"),
        "img[alt='KIỂM TRA'], button[type='submit'], form button",
        result_selectors=("[data-sonner-toast]", "#enter-code-code ~ [role='alert']", "form [role='alert']", ".swal2-container", ".toast", "[class*='result' i]"),
        success_markers=_COMMON_SUCCESS, failure_markers=_COMMON_FAILURE,
        tab_slots=2, form_settle_seconds=0.05, result_timeout_ms=4000,
        result_poll_interval=0.05, selector_fast_window_seconds=0.60,
        full_reload_every=150,
    ),
    "liverr88.net": SiteProfile(
        "liverr88.net", "https://liverr88.net/nhap-code",
        # Ô tài khoản: <input id="enter-code-username" aria-label="Tên tài khoản">
        ("#enter-code-username", "input[aria-label='Tên tài khoản']",
         "input[placeholder='Tên tài khoản']", "#username", "#account-code",
         "input[name='username']"),
        # Ô mã: <input id="enter-code-code" aria-label="Mã code">
        ("#enter-code-code", "input[aria-label='Mã code']",
         "input[placeholder='Nhập mã code']", "#code", "input[name='code']"),
        # Nút gửi: <button type="submit">Kiểm tra</button>
        "button[type='submit'], form button, button.code-submit-btn",
        result_selectors=(
            "[data-sonner-toast]", "#enter-code-code ~ [role='alert']",
            ".alert-modal-overlay", ".alert-modal-wc", ".Toastify__toast",
            "form [role='alert']", "form [role='status']", ".swal2-container",
            ".toast", "[class*='result' i]",
        ),
        success_markers=_COMMON_SUCCESS, failure_markers=_COMMON_FAILURE,
        # RR88 chạy hai tab/account song song giống MM88, XX88 và GG88.
        tab_slots=2, form_settle_seconds=0.03, result_timeout_ms=3500,
        result_poll_interval=0.05, selector_fast_window_seconds=0.60,
        full_reload_every=150,
        popup_dismiss_selectors=("button.alert-modal-wc-accept-btn", "button[aria-label='Xác nhận']"),
    ),
    "xx88code.com": SiteProfile(
        "xx88code.com", "https://xx88code.com",
        ("input[placeholder='Nhập tài khoản']", "#account-code", "input[name='username']"),
        ("input[placeholder='Mã code']", "input[autocomplete='one-time-code']"),
        "button[aria-label='Kiểm tra ngay'], button[type='submit'], form button",
        result_selectors=(
            "img[src$='/images/ui-aquarium/btn-accept.png']",
            "form [role='alert']", "form [role='status']", ".swal2-container",
            ".toast", "[class*='result' i]",
        ),
        success_markers=_COMMON_SUCCESS,
        failure_markers=_COMMON_FAILURE + (
            "code đã sử dụng hết",
            "code đã hết hạn",
            "mã đã được sử dụng",
            "mã đã hết hạn",
            "code used up",
            "code has expired",
        ),
        tab_slots=2, form_settle_seconds=0.01, result_timeout_ms=3500,
        result_poll_interval=0.02, selector_fast_window_seconds=0.15,
        full_reload_every=200,
        public_api_endpoint="https://api.xx88code.com/codes/use-code-public",
        api_response_timeout_ms=4500,
        # Popup XX88 dùng nút cha aria-label="Xác nhận" và ảnh con btn-accept.
        # Ưu tiên click button; selector ảnh là fallback khi DOM chỉ expose img.
        popup_dismiss_selectors=(
            "button[aria-label='Xác nhận']",
            "img[src$='/images/ui-aquarium/btn-accept.png']",
            "button[aria-label='Thử lại']",
            "button[aria-label='Đóng']",
        ),
    ),
    "gg88live.tv": SiteProfile(
        "gg88live.tv", "https://gg88live.tv/nhap-code",
        ("#enter-code-username", "input[name='username']", "input[placeholder='Nhập tên người dùng']"),
        ("#enter-code-code", "input[name='code']", "input[placeholder='Nhập mã code']", "input[autocomplete='one-time-code']"),
        "button[aria-label='Kiểm tra'], button[type='submit'], form button",
        result_selectors=("[data-sonner-toast]", "form [role='alert']", "form [role='status']", ".modal-content", ".swal2-container", ".toast", "[class*='result' i]"),
        success_markers=_COMMON_SUCCESS, failure_markers=_COMMON_FAILURE,
        tab_slots=2, form_settle_seconds=0.02, result_timeout_ms=3500,
        result_poll_interval=0.05, selector_fast_window_seconds=0.50,
        full_reload_every=200,
    ),
    "o8code.com": SiteProfile(
        "o8code.com", "https://o8code.com",
        ("input[placeholder='Nhập tên người dùng']", "#account-code", "input[name='username']"),
        ("input[placeholder='Nhập mã code']", "input[autocomplete='one-time-code']"),
        ".modal-submit-wrap button, button[type='submit']",
        result_selectors=(".modal-submit-wrap ~ [role='alert']", ".modal [role='alert']", ".swal2-container", ".toast", "[class*='result' i]"),
        success_markers=_COMMON_SUCCESS, failure_markers=_COMMON_FAILURE,
        tab_slots=1, form_settle_seconds=0.02, result_timeout_ms=3000,
        result_poll_interval=0.05, selector_fast_window_seconds=0.50,
        full_reload_every=200,
    ),
}


def get_site_profile(domain: str) -> SiteProfile | None:
    raw = (domain or "").strip().lower()
    if not raw:
        return None
    if "://" in raw:
        raw = urlparse(raw).hostname or ""
    else:
        raw = raw.split("/", 1)[0]
    raw = raw.removeprefix("www.").strip(".")
    return SITE_PROFILES.get(raw)


def validate_profiles(profiles: Mapping[str, SiteProfile] = SITE_PROFILES) -> dict[str, list[str]]:
    return {domain: errors for domain, profile in profiles.items() if (errors := profile.validate())}


_PROFILE_ERRORS = validate_profiles()
if _PROFILE_ERRORS:
    raise ValueError(f"SITE_PROFILES invalid: {_PROFILE_ERRORS}")


def browser_domains() -> frozenset[str]:
    return frozenset(SITE_PROFILES)


__all__ = ["SiteProfile", "SITE_PROFILES", "get_site_profile", "validate_profiles", "browser_domains"]
